# Sidebar navigation

- label: 'Main'
  link: '/'
- label: 'About Us'
  link: '/usage/about-us'
- label: 'FAQ'
  link: '/usage/faq'
- label: 'KRL'
  link: '/usage/krl'
- label: 'Moonray'
  link: '/usage/moonray'

